site_name: NTU ROBOTICS
site_description: Club documentation page
site_author: ket3l4
theme: 
  name: material
  language: en

nav:
  - About Us: index.md
  - Projects:
      - Robot Arm: projects/arm.md
      - Rover: projects/rover.md
      - Frisbee Thrower: projects/frisbee.md